export const defaultCharacter = {
  name: 'New Character',
  class: 'Fighter',
  subclass: '',
  race: '',
  background: '',
  alignment: '',
  level: 1,
  experiencePoints: 0,
  abilities: { str: 10, dex: 10, con: 10, int: 10, wis: 10, cha: 10 },
  savingThrowProficiencies: { str: false, dex: false, con: false, int: false, wis: false, cha: false },
  skillProficiencies: {},
  hp: { max: 10, current: 10, temp: 0 },
  ac: 10,
  speed: 30,
  initiativeBonus: 0,
  hitDice: { total: 1, remaining: 1, die: 'd10' },
  deathSaves: { successes: 0, failures: 0 },
  attacks: [],
  conditions: [],
  concentration: null,
  features: '',
  equipment: '',
  notes: '',
  personality: '',
  ideals: '',
  bonds: '',
  flaws: '',
  spells: {
    spellcastingAbility: 'int',
    prepared: [],
    slots: {},
  },
  currency: { cp: 0, sp: 0, ep: 0, gp: 0, pp: 0 },
  resources: [],
};
