export const HP_AVERAGE = { d6: 4, d8: 5, d10: 6, d12: 7 };

export const ASI_LEVELS = {
  barbarian: [4, 8, 12, 16, 19],
  bard:      [4, 8, 12, 16, 19],
  cleric:    [4, 8, 12, 16, 19],
  druid:     [4, 8, 12, 16, 19],
  fighter:   [4, 6, 8, 12, 14, 16, 19],
  monk:      [4, 8, 12, 16, 19],
  paladin:   [4, 8, 12, 16, 19],
  ranger:    [4, 8, 12, 16, 19],
  rogue:     [4, 8, 10, 12, 16, 19],
  sorcerer:  [4, 8, 12, 16, 19],
  warlock:   [4, 8, 12, 16, 19],
  wizard:    [4, 8, 12, 16, 19],
};

export const isAsiLevel = (cls, level) =>
  (ASI_LEVELS[(cls || '').toLowerCase()] || []).includes(level);

export const CLASS_FEATURES = {
  barbarian: {
    1:  ['Rage', 'Unarmored Defense'],
    2:  ['Reckless Attack', 'Danger Sense'],
    3:  ['Primal Path (subclass)'],
    4:  ['ASI or Feat'],
    5:  ['Extra Attack', 'Fast Movement (+10 ft)'],
    6:  ['Primal Path feature'],
    7:  ['Feral Instinct (advantage on initiative)'],
    8:  ['ASI or Feat'],
    9:  ['Brutal Critical (1 extra die)'],
    10: ['Primal Path feature'],
    11: ['Relentless Rage'],
    12: ['ASI or Feat'],
    13: ['Brutal Critical (2 extra dice)'],
    14: ['Primal Path feature'],
    15: ['Persistent Rage'],
    16: ['ASI or Feat'],
    17: ['Brutal Critical (3 extra dice)'],
    18: ['Indomitable Might'],
    19: ['ASI or Feat'],
    20: ['Primal Champion (+4 STR, +4 CON)'],
  },
  bard: {
    1:  ['Bardic Inspiration (d6)', 'Spellcasting'],
    2:  ['Jack of All Trades', 'Song of Rest (d6)'],
    3:  ['Bard College (subclass)', 'Expertise ×2'],
    4:  ['ASI or Feat'],
    5:  ['Bardic Inspiration → d8', 'Font of Inspiration (regain on short rest)'],
    6:  ['Countercharm', 'College feature'],
    8:  ['ASI or Feat'],
    9:  ['Song of Rest → d8'],
    10: ['Bardic Inspiration → d10', 'Expertise ×2 more', 'Magical Secrets (any 2 spells)'],
    12: ['ASI or Feat'],
    13: ['Song of Rest → d10'],
    14: ['Magical Secrets (2 more)', 'College feature'],
    15: ['Bardic Inspiration → d12'],
    16: ['ASI or Feat'],
    17: ['Song of Rest → d12'],
    18: ['Magical Secrets (2 more)'],
    19: ['ASI or Feat'],
    20: ['Superior Inspiration (regain 1 use on initiative if 0 left)'],
  },
  cleric: {
    1:  ['Spellcasting', 'Divine Domain (subclass)'],
    2:  ['Channel Divinity (1/rest)', 'Domain feature'],
    4:  ['ASI or Feat'],
    5:  ['Destroy Undead (CR ½)'],
    6:  ['Channel Divinity (2/rest)', 'Domain feature'],
    8:  ['ASI or Feat', 'Destroy Undead (CR 1)', 'Domain feature'],
    10: ['Divine Intervention'],
    11: ['Destroy Undead (CR 2)'],
    12: ['ASI or Feat'],
    14: ['Destroy Undead (CR 3)'],
    16: ['ASI or Feat'],
    17: ['Destroy Undead (CR 4)', 'Domain feature'],
    18: ['Channel Divinity (3/rest)'],
    19: ['ASI or Feat'],
    20: ['Improved Divine Intervention (auto-success)'],
  },
  druid: {
    1:  ['Druidic', 'Spellcasting'],
    2:  ['Wild Shape (CR ¼)', 'Druid Circle (subclass)'],
    4:  ['ASI or Feat', 'Wild Shape → CR ½ (swim), no flying'],
    6:  ['Circle feature'],
    8:  ['ASI or Feat', 'Wild Shape → CR 1 (fly allowed)'],
    10: ['Circle feature'],
    12: ['ASI or Feat'],
    14: ['Circle feature'],
    16: ['ASI or Feat'],
    18: ['Timeless Body', 'Beast Spells (cast spells in Wild Shape)'],
    19: ['ASI or Feat'],
    20: ['Archdruid (unlimited Wild Shape)'],
  },
  fighter: {
    1:  ['Fighting Style', 'Second Wind'],
    2:  ['Action Surge (1/rest)'],
    3:  ['Martial Archetype (subclass)'],
    4:  ['ASI or Feat'],
    5:  ['Extra Attack'],
    6:  ['ASI or Feat'],
    7:  ['Archetype feature'],
    8:  ['ASI or Feat'],
    9:  ['Indomitable (1/long rest)'],
    10: ['Archetype feature'],
    11: ['Extra Attack (3 total)'],
    12: ['ASI or Feat'],
    13: ['Indomitable (2/long rest)'],
    14: ['ASI or Feat'],
    15: ['Archetype feature'],
    16: ['ASI or Feat'],
    17: ['Action Surge (2/rest)', 'Indomitable (3/long rest)'],
    18: ['Archetype feature'],
    19: ['ASI or Feat'],
    20: ['Extra Attack (4 total)'],
  },
  monk: {
    1:  ['Unarmored Defense', 'Martial Arts (d4)'],
    2:  ['Ki Points', 'Unarmored Movement (+10 ft)', 'Flurry of Blows', 'Patient Defense', 'Step of the Wind'],
    3:  ['Monastic Tradition (subclass)', 'Deflect Missiles'],
    4:  ['ASI or Feat', 'Slow Fall'],
    5:  ['Extra Attack', 'Stunning Strike', 'Martial Arts → d6'],
    6:  ['Ki-Empowered Strikes', 'Tradition feature'],
    7:  ['Evasion', 'Stillness of Mind'],
    8:  ['ASI or Feat'],
    9:  ['Unarmored Movement (+15 ft)'],
    10: ['Purity of Body (disease & poison immunity)', 'Martial Arts → d8'],
    11: ['Tradition feature'],
    12: ['ASI or Feat'],
    13: ['Tongue of Sun and Moon', 'Unarmored Movement (+20 ft)'],
    14: ['Diamond Soul (proficiency in all saves, reroll 1/rest)'],
    15: ['Timeless Body', 'Martial Arts → d10'],
    16: ['ASI or Feat'],
    17: ['Tradition feature', 'Unarmored Movement (+25 ft)'],
    18: ['Empty Body (invisible + astral projection)'],
    19: ['ASI or Feat'],
    20: ['Perfect Self (regain 4 Ki on initiative if 0)', 'Martial Arts → d12'],
  },
  paladin: {
    1:  ['Divine Sense', 'Lay on Hands'],
    2:  ['Fighting Style', 'Spellcasting', 'Divine Smite'],
    3:  ['Divine Health (disease immunity)', 'Sacred Oath (subclass)'],
    4:  ['ASI or Feat'],
    5:  ['Extra Attack'],
    6:  ['Aura of Protection (CHA mod to saves, 10 ft)'],
    7:  ['Sacred Oath feature'],
    8:  ['ASI or Feat'],
    10: ['Aura of Courage (immunity to frightened aura, 10 ft)'],
    11: ['Improved Divine Smite (+1d8 radiant on all melee hits)'],
    12: ['ASI or Feat'],
    14: ['Cleansing Touch (dispel magic using Lay on Hands action)'],
    15: ['Sacred Oath feature'],
    16: ['ASI or Feat'],
    18: ['Auras expand to 30 ft'],
    19: ['ASI or Feat'],
    20: ['Sacred Oath capstone'],
  },
  ranger: {
    1:  ['Favored Enemy', 'Natural Explorer'],
    2:  ['Fighting Style', 'Spellcasting'],
    3:  ['Ranger Archetype (subclass)', 'Primeval Awareness'],
    4:  ['ASI or Feat'],
    5:  ['Extra Attack'],
    6:  ['Favored Enemy & Natural Explorer improvements'],
    7:  ['Archetype feature'],
    8:  ["ASI or Feat", "Land's Stride (no difficult terrain cost, no plant damage)"],
    10: ['Natural Explorer (3rd terrain)', 'Hide in Plain Sight'],
    11: ['Archetype feature'],
    12: ['ASI or Feat'],
    14: ["Vanish (Hide as bonus action, can't be tracked non-magically)"],
    15: ['Archetype feature'],
    16: ['ASI or Feat'],
    18: ['Feral Senses (detect invisible within 30 ft)'],
    19: ['ASI or Feat'],
    20: ['Foe Slayer (+WIS to attack or damage vs. favored enemy, 1/turn)'],
  },
  rogue: {
    1:  ['Expertise ×2', 'Sneak Attack (1d6)', "Thieves' Cant"],
    2:  ['Cunning Action'],
    3:  ['Roguish Archetype (subclass)', 'Sneak Attack → 2d6'],
    4:  ['ASI or Feat'],
    5:  ['Uncanny Dodge', 'Sneak Attack → 3d6'],
    6:  ['Expertise ×2 more'],
    7:  ['Evasion', 'Sneak Attack → 4d6'],
    8:  ['ASI or Feat'],
    9:  ['Archetype feature', 'Sneak Attack → 5d6'],
    10: ['ASI or Feat'],
    11: ['Reliable Talent', 'Sneak Attack → 6d6'],
    12: ['ASI or Feat'],
    13: ['Archetype feature', 'Sneak Attack → 7d6'],
    14: ['Blindsense (30 ft)', 'Sneak Attack → 7d6'],
    15: ['Slippery Mind (WIS save proficiency)', 'Sneak Attack → 8d6'],
    16: ['ASI or Feat'],
    17: ['Archetype feature', 'Sneak Attack → 9d6'],
    18: ['Elusive (no advantage on attacks against you unless incapacitated)'],
    19: ['ASI or Feat', 'Sneak Attack → 10d6'],
    20: ['Stroke of Luck (turn miss/fail into success, 1/rest)'],
  },
  sorcerer: {
    1:  ['Sorcerous Origin (subclass)', 'Spellcasting'],
    2:  ['Font of Magic (Sorcery Points = level)'],
    3:  ['Metamagic (choose 2)'],
    4:  ['ASI or Feat'],
    6:  ['Origin feature'],
    8:  ['ASI or Feat'],
    10: ['Metamagic (3rd option)'],
    12: ['ASI or Feat'],
    14: ['Origin feature'],
    16: ['ASI or Feat'],
    17: ['Metamagic (4th option)'],
    18: ['Origin feature'],
    19: ['ASI or Feat'],
    20: ['Sorcerous Restoration (regain 4 Sorcery Points on short rest)'],
  },
  warlock: {
    1:  ['Otherworldly Patron (subclass)', 'Pact Magic', 'Eldritch Invocations (2)'],
    2:  ['Eldritch Invocations (3 total)'],
    3:  ['Pact Boon', 'Eldritch Invocations (4)'],
    4:  ['ASI or Feat', 'Eldritch Invocations (5)'],
    6:  ['Patron feature', 'Eldritch Invocations (6)'],
    8:  ['ASI or Feat', 'Eldritch Invocations (7)'],
    10: ['Patron feature', 'Eldritch Invocations (8)'],
    11: ['Mystic Arcanum (6th-level spell, 1/long rest)', 'Eldritch Invocations (8)'],
    12: ['ASI or Feat'],
    13: ['Mystic Arcanum (7th-level spell, 1/long rest)'],
    14: ['Patron feature'],
    15: ['Mystic Arcanum (8th-level spell, 1/long rest)'],
    16: ['ASI or Feat'],
    17: ['Mystic Arcanum (9th-level spell, 1/long rest)'],
    19: ['ASI or Feat'],
    20: ['Eldritch Master (regain all Pact Magic on 1-min ritual)'],
  },
  wizard: {
    1:  ['Arcane Recovery (regain slots ≤ ½ level on short rest)', 'Spellcasting'],
    2:  ['Arcane Tradition (subclass)'],
    4:  ['ASI or Feat'],
    6:  ['Tradition feature'],
    8:  ['ASI or Feat'],
    10: ['Tradition feature'],
    12: ['ASI or Feat'],
    14: ['Tradition feature'],
    16: ['ASI or Feat'],
    18: ['Spell Mastery (one 1st- and one 2nd-level spell at will)'],
    19: ['ASI or Feat'],
    20: ['Signature Spells (two instant-prep 3rd-level spells, 1/short rest each)'],
  },
};

export const FEATS = [
  { name: 'Alert', prerequisite: null, description: '+5 to initiative. Cannot be surprised while conscious. Hidden creatures gain no advantage on attacks against you.', abilityBonus: null },
  { name: 'Athlete', prerequisite: null, description: 'Climbing costs no extra movement. Stand from prone uses only 5 ft. Make a running long jump from only a 5 ft move. +1 STR or DEX.', abilityBonus: { type: 'choice', options: ['str','dex'], amount: 1 } },
  { name: 'Actor', prerequisite: null, description: 'Advantage on Deception and Performance for impersonation. Mimic speech or sounds you\'ve heard (DC 15 Insight to detect). +1 CHA.', abilityBonus: { type: 'fixed', ability: 'cha', amount: 1 } },
  { name: 'Charger', prerequisite: null, description: 'After Dashing, use a bonus action to make one melee attack or shove. If you moved ≥10 ft toward the target, +5 damage or push 10 ft.', abilityBonus: null },
  { name: 'Crossbow Expert', prerequisite: null, description: 'Ignore the loading property of crossbows. No disadvantage for ranged attacks in melee. When you attack with a hand crossbow, use a bonus action to attack with it again.', abilityBonus: null },
  { name: 'Defensive Duelist', prerequisite: 'Dexterity 13+', description: 'When hit by a melee attack while wielding a finesse weapon you\'re proficient with, use your reaction to add your proficiency bonus to AC for that attack.', abilityBonus: null },
  { name: 'Dual Wielder', prerequisite: null, description: '+1 AC while wielding a melee weapon in each hand. Two-weapon fighting without the light property. Draw or stow two weapons at once.', abilityBonus: null },
  { name: 'Dungeon Delver', prerequisite: null, description: 'Advantage to notice secret doors. Advantage on checks to detect traps. Resistance to trap damage. Search for traps at normal travel pace.', abilityBonus: null },
  { name: 'Durable', prerequisite: null, description: 'When spending hit dice, minimum regained = 2× CON modifier (min 2). +1 CON.', abilityBonus: { type: 'fixed', ability: 'con', amount: 1 } },
  { name: 'Elemental Adept', prerequisite: 'Ability to cast a spell', description: 'Choose acid, cold, fire, lightning, or thunder. Spells of that type ignore resistance. Treat any 1 on a damage die as a 2.', abilityBonus: null },
  { name: 'Grappler', prerequisite: 'Strength 13+', description: 'Advantage on attack rolls vs. a creature you\'re grappling. Use an action to pin a grappled creature (both restrained).', abilityBonus: null },
  { name: 'Great Weapon Master', prerequisite: null, description: 'On a crit or killing blow with a heavy weapon, make one melee attack as a bonus action. Take −5 to attack roll for +10 damage with heavy weapons.', abilityBonus: null },
  { name: 'Healer', prerequisite: null, description: "Stabilize with a healer's kit and restore 1 HP. Use the kit to restore 1d6 + 4 + max hit dice HP (once per short rest per creature).", abilityBonus: null },
  { name: 'Heavily Armored', prerequisite: 'Proficiency with medium armor', description: 'Gain heavy armor proficiency. +1 STR.', abilityBonus: { type: 'fixed', ability: 'str', amount: 1 } },
  { name: 'Heavy Armor Master', prerequisite: 'Proficiency with heavy armor', description: 'While wearing heavy armor, nonmagical B/P/S damage is reduced by 3. +1 STR.', abilityBonus: { type: 'fixed', ability: 'str', amount: 1 } },
  { name: 'Inspiring Leader', prerequisite: 'Charisma 13+', description: 'Spend 10 min inspiring ≤6 allies. Each gains temp HP = level + CHA modifier. Refreshes on short or long rest.', abilityBonus: null },
  { name: 'Keen Mind', prerequisite: null, description: 'Always know true north and hours to sunrise/sunset. Accurately recall anything seen or heard in the past month. +1 INT.', abilityBonus: { type: 'fixed', ability: 'int', amount: 1 } },
  { name: 'Lightly Armored', prerequisite: null, description: 'Gain light armor proficiency. +1 STR or DEX.', abilityBonus: { type: 'choice', options: ['str','dex'], amount: 1 } },
  { name: 'Linguist', prerequisite: null, description: 'Learn 3 languages. Create ciphers only those who know the system can decode. +1 INT.', abilityBonus: { type: 'fixed', ability: 'int', amount: 1 } },
  { name: 'Lucky', prerequisite: null, description: '3 luck points per long rest. Spend to roll an extra d20 on an attack, ability check, or save (choose which die). Or impose disadvantage on an attack against you.', abilityBonus: null },
  { name: 'Mage Slayer', prerequisite: null, description: 'Reaction to attack a caster within 5 ft who casts a spell. That creature has disadvantage on concentration saves. Advantage on saves vs. spells cast by creatures within 5 ft.', abilityBonus: null },
  { name: 'Magic Initiate', prerequisite: null, description: 'Choose a class. Learn 2 cantrips and one 1st-level spell from that class, cast once per long rest without a slot (using that class\'s spellcasting ability).', abilityBonus: null },
  { name: 'Martial Adept', prerequisite: null, description: 'Learn 2 maneuvers from the Battle Master list. Gain 1 superiority die (d6). Refreshes on short or long rest.', abilityBonus: null },
  { name: 'Medium Armor Master', prerequisite: 'Proficiency with medium armor', description: 'Medium armor no longer imposes Stealth disadvantage. Max DEX bonus to AC from medium armor increases to +3.', abilityBonus: null },
  { name: 'Mobile', prerequisite: null, description: 'Speed increases by 10 ft. Dash ignores difficult terrain cost. Melee attacks don\'t provoke opportunity attacks from the target.', abilityBonus: null },
  { name: 'Moderately Armored', prerequisite: 'Proficiency with light armor', description: 'Gain medium armor and shield proficiency. +1 STR or DEX.', abilityBonus: { type: 'choice', options: ['str','dex'], amount: 1 } },
  { name: 'Mounted Combatant', prerequisite: null, description: 'Advantage on melee attacks vs. unmounted creatures smaller than your mount. Force attacks to target you instead of mount. Mount takes no damage on successful DEX save.', abilityBonus: null },
  { name: 'Observant', prerequisite: null, description: 'Lip-reading if you can see a creature\'s mouth. +5 to passive Perception and passive Investigation. +1 INT or WIS.', abilityBonus: { type: 'choice', options: ['int','wis'], amount: 1 } },
  { name: 'Polearm Master', prerequisite: null, description: 'Bonus action attack with butt of glaive, halberd, pike, or quarterstaff (1d4 bludgeoning). Creatures entering your reach provoke an opportunity attack.', abilityBonus: null },
  { name: 'Resilient', prerequisite: null, description: '+1 to a chosen ability score. Gain proficiency in saving throws using that ability.', abilityBonus: { type: 'choice', options: ['str','dex','con','int','wis','cha'], amount: 1 } },
  { name: 'Ritual Caster', prerequisite: 'Intelligence or Wisdom 13+', description: 'Acquire a ritual book with 2 ritual spells from a chosen class. Add ritual spells found during adventures. Cast any ritual in the book.', abilityBonus: null },
  { name: 'Savage Attacker', prerequisite: null, description: 'Once per turn when rolling melee weapon damage, reroll the damage dice and use either result.', abilityBonus: null },
  { name: 'Sentinel', prerequisite: null, description: 'Opportunity attacks reduce speed to 0. Can make OAs even if target Disengages. Reaction attack when a creature within 5 ft attacks a different creature.', abilityBonus: null },
  { name: 'Sharpshooter', prerequisite: null, description: 'No disadvantage at long range. Ignore half and three-quarters cover. Take −5 to attack roll for +10 damage.', abilityBonus: null },
  { name: 'Shield Master', prerequisite: null, description: 'Bonus action shove after taking the Attack action. Add shield bonus to DEX saves targeting only you. Successful DEX save = no damage (normally half).', abilityBonus: null },
  { name: 'Skilled', prerequisite: null, description: 'Gain proficiency in any 3 skills or tools.', abilityBonus: null },
  { name: 'Skulker', prerequisite: 'Dexterity 13+', description: 'Hide when lightly obscured. Missed ranged attacks don\'t reveal your position. Dim light doesn\'t impose disadvantage on Perception checks.', abilityBonus: null },
  { name: 'Spell Sniper', prerequisite: 'Ability to cast a spell', description: 'Double range of attack-roll spells. Ignore half and three-quarters cover. Learn one attack-roll cantrip.', abilityBonus: null },
  { name: 'Tavern Brawler', prerequisite: null, description: 'Proficient with improvised weapons. Unarmed strikes deal 1d4. After hitting with an unarmed strike or improvised weapon, bonus action grapple attempt. +1 STR or CON.', abilityBonus: { type: 'choice', options: ['str','con'], amount: 1 } },
  { name: 'Tough', prerequisite: null, description: 'HP maximum increases by 2 per level (retroactive). Future level-ups also grant +2 HP.', abilityBonus: { type: 'tough' } },
  { name: 'War Caster', prerequisite: 'Ability to cast at least one spell', description: 'Advantage on CON saves to maintain concentration. Perform somatic components while holding weapons or shield. Cast a spell as an opportunity attack.', abilityBonus: null },
  { name: 'Weapon Master', prerequisite: null, description: 'Gain proficiency with 4 weapons of your choice. +1 STR or DEX.', abilityBonus: { type: 'choice', options: ['str','dex'], amount: 1 } },
];
